document.querySelector('p').style.color = 'red';
document.querySelector('p').style.fontSize = 'small'
document.querySelector('h2').innerText = 'Shrek 2';
document.querySelectorAll('p')[1].innerText = 'Usando minha criatividade para alterar o segundo parágrafo.';
document.querySelectorAll('p')[1].style.color = 'purple';
document.querySelectorAll('p')[1].innerText = document.querySelectorAll('p')[1].innerText.toUpperCase();
document.querySelectorAll('p')[1].style.fontWeight = '200';
document.querySelector('h4').innerText = 'Olha a minha criatividade';
document.querySelector('h4').style.fontWeight = '800';
document.querySelector('h4').style.fontSize = 'larger';
document.querySelector('h4').style.color = 'green';
